# Generated by Django 4.2.9 on 2024-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
