# Generated by Django 4.2.9 on 2024-06-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/video/'),
        ),
    ]
