# Generated by Django 4.2.9 on 2024-06-20 21:58

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_posts_image_alter_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.post_directory_path),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.post_directory_path),
        ),
    ]
