# Generated by Django 4.2.9 on 2024-04-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(blank=True, default='/static/images/cover_pic.png', null=True, upload_to=''),
        ),
    ]
