# Generated by Django 4.2.9 on 2024-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, default='default/cover_pic.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(blank=True, default='default/pro_pic.png', null=True, upload_to=''),
        ),
    ]
