# Generated by Django 4.2.9 on 2024-05-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_chatroom_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-id']},
        ),
    ]
