# Generated by Django 4.2.9 on 2024-06-14 14:37

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, default='images/cover_pic.png', null=True, upload_to=base.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(blank=True, default='images/pro_pic.png', null=True, upload_to=base.models.user_directory_path),
        ),
    ]
